services:
  cutclip-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - database:/app/prisma
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/prod.db
      - NEXT_TELEMETRY_DISABLED=1
      - CHECKPOINT_DISABLE=1
      - DISABLE_PRISMA_TELEMETRY=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  database:
    driver: local